spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: um
    password: um123
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pasechnik.o.n@gmail.com
    password: 11
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true

server:
  port: 8081

logging:
  level:
    root: INFO